Removed suport to avro
opendatamesh-initiative/odm-platform-adapter-observer-blindata pull request #17
Opened 2024-06-25 07:50 UTC by AGFaro

2024-06-25 08:08 UTC, gabrielefantini commented on README.md
> +configurations, as shown in the previous section.
Qui dove sono le regex?

2024-06-25 08:39 UTC, gabrielefantini commented on README.md
> +In Blindata's Data Store API Mapping, additional properties are structured with the field name as the key and its
Questo è scritto male, non si capisce

2024-06-25 08:40 UTC, gabrielefantini commented on README.md
> +#### Multiple Entities Schema
Ma questi non asono async API !!!!!

2024-06-27 07:16 UTC, GiuliaBusnelli commented on README.md
> +purpose of this adapter is to keep the business glossary within Blindata constantly updated. Upon the occurrence of a
Non è il business glossary che si tiene aggiornato...

2024-06-27 07:18 UTC, GiuliaBusnelli requested changes

2024-06-27 07:18 UTC, GiuliaBusnelli commented on meta-service-blindata/odm-platform-up-meta-service-blindata.iml
Questo file, insieme agli altri due .iml, devi rimuoverli dal repo remoto

2024-06-27 07:21 UTC, GiuliaBusnelli commented on README.md
> +3. [Metadata Mapping in Blindata](#metadata-mapping-in-blindata)
Il link non funziona

2024-06-27 07:22 UTC, GiuliaBusnelli commented on README.md
> +         - [Physical Entity](#physical-entity)
Il link riporta al paragrafo sbagliato (quello sotto Datastore API, perchè hanno lo stesso id...)

2024-06-27 07:22 UTC, GiuliaBusnelli commented on README.md
> +         - [Physical Field](#physical-field)
Come sopra, il link riporta al paragrafo sbagliato

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +      address: The address of ODM Notification Service
Cos'è questa riga? Penso sia parte della configurazione per ODM...

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +4. [Prerequisites](#prerequisites)
Tutta la parte su come eseguire il progetto la metterei sotto un'unico cappello, tipo "Run the project"
Sposterei anche le due sezioni con le configurazioni prima di "Test it", sotto il titolo "Configure the project" o qualcosa di simile

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +## Mapping in Blindata
Aggiungere due righe sul fatto che, dato un descriptor, lato Blindata vengono creati i sistemi, le physical entities e i physical fields

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +##### Physical Entity
Modificare in "From JSONSchema to Physical Entities".
Aggiornare l'indice.
Verificare il livello del titolo (4 o 5 #? bisogna rimanere coerenti con i successivi)

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +#### Physical Field
Modificare in "From JSONSchema to Physical Fields".
Aggiornare l'indice.
Verificare il livello del titolo (4 o 5 #? bisogna rimanere coerenti con il precedente e i successivi)

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +Physical entities can be find in "channel.message" section of the descriptor.
Perchè qua parli di physical entities?

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +##### From Avro to Physical Entity
Physical Entities

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +##### From Avro to Physical Field
Physical Fields

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +This section provides examples of how to represent a single entity using the Data Store API. It demonstrates the application of schema annotations to define multiple physical entities and their field
Perchè parli di "multiple physical entities" se sei nel caso della singola?

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +This section illustrates an example of an Async API version 3 configuration for a Trip Status Streaming API. The API is used to stream events related to the Trip entity. It describes the schema for t
Non commenti quali risorse vengono create in Blindata a fronte di questo descriptor.

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +This section provides an example of an Async API version 2 configuration for a Trip Status Streaming API. It includes details on the servers, channels, and message schemas used for streaming events r
Non commenti quali risorse vengono create in Blindata a fronte di questo descriptor.

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +#### Entities Async Api V3
Manca il commento dell'esempio

2024-07-04 07:25 UTC, GiuliaBusnelli commented on README.md
> +#### Entities Async Api V2
Manca il commento dell'esempio

2024-07-09 07:19 UTC, merged